### ISSUE TITLE
Napaka v shiny okencu

### ISSUE THREAD

**Issue by mpracek** [mpracek/matematika-z-racunalnikom#2]
Pri odpiranju Shiny vmesnika se na okencu *Razumevanje rojstno-smrtnih procesov* pojavi napis *unused arguments*, ki ga ne znam odpraviti.

**Comment by mpracek** [comment]
Napako sem odpravil, sedaj se mi pojavi nova napaka, in sicer 
`
Warning: Error in porazdelitve[[stevilka_porazdelitve]]: attempt to apply non-function
 215: smrti [../osnova/osnovne_funkcije.r#38]
  214: stevilo [../osnova/osnovne_funkcije.r#56]
  213: animacija_obicajna [../vizualizacija/animacija.r#26]
  212: eventReactiveHandler [C:\Users\Lenovo_Uporabnik\Desktop\FMF\Magisterij\Matematika_z_racunalnikom\matematika-z-racunalnikom\shiny/server.R#24]
`

**Comment by matijapretnar** [comment]
Pozdravljeni, težava v funkciji `smrti` in `rojstva` je, da je `stevilka_porazdelitve` niz (`"1"`, `"2"`, ...) in zato ne morete vzeti ustreznega indeksa.

**Comment by mpracek** [comment]
Hvala vam za pomoč, napake sem odpravil.
