### ISSUE TITLE
Vizualizacija

### ISSUE THREAD

**Issue by mpracek** [mpracek/matematika-z-racunalnikom#3]
V mapi vizualizacija se nahaja datoteka *animacija.R*. V tej datoteki želim prikazati vizualizacijo celotne igre življenja. Ker za vizualizacijo matrik v obliki, potrebni za predstavitev življenja potrebujem navadno funkcijo plot, se mi pojavi problem. Igre življenja ne morem predstaviti skozi vse korake, saj skozi zanko plot objektov ne morem sproti shranjevati. Zato Igre ne morem v celoti predstaviti.
```
narisi_igro <- function(st_korakov, zacetna_matrika){
 #črni kvadratki so mrtve celice
#modri kvadratki so žive celice
rezultat <- celotna_igra(st_korakov, zacetna_matrika)
 for(i in 1:length(rezultat)){
    p <- plot(rezultat[[i]], col = c("blue","black"),
         main = sprintf("Igra v %d koraku",i),
         xlab = "", ylab ="")
    print(p)
    }
}
```

**Comment by matijapretnar** [comment]
Kaj pa, če grafov ne narišete v zanki, temveč po izvedeni simulaciji (`rezultat <- celotna_igra(...)`) uporabniku ponudite drsnik od `1` do `st_korakov`, nato pa sproti narišete graf za izbrani korak?

**Comment by mpracek** [comment]
Hvala vam za pomoč, napake sem odpravil in našel drugi način prikaza.

**Comment by matijapretnar** [comment]
Zdaj dela, moram pa reči, da za uporabnika ni najbolj prijazen vmesnik. Običajno pri igri življenja želimo videti, kako se vzorec spreminja. Tu pa je treba za vsak korak popraviti številko in še enkrat pognati simulacijo.

**Comment by mpracek** [comment]
Ravno v času, ko ste odgovorili, sem se ukvarjal s tem problemom in ga sedaj tudi odpravil.
